baseURL = "http://yuqar-group.com/"
languageCode = "en-us"
title = "YuQar Group"
theme = "binario"
paginate = 10

[Params]
  description = "Responsive card-based & code-light Hugo theme"
  columns = 2
